// Generated by https://quicktype.io

import { ProductsModule } from "../products.module";

export interface IProduct {
  precio:           number;
  id?:              number;
  title:            string;
  image:            string;
  stock:            number;
  empresa:          string;
  especificaciones?: { [key: string]: string };
}